//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayLocNuoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public comment()
        {
            this.liKe1 = new HashSet<liKe1>();
        }
    
        public int idCM { get; set; }
        public string noidung { get; set; }
        public Nullable<int> solike { get; set; }
        public Nullable<int> idDG { get; set; }
        public Nullable<bool> daxoa { get; set; }
        public string taikhoan { get; set; }
    
        public virtual acc acc { get; set; }
        public virtual danhgia danhgia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<liKe1> liKe1 { get; set; }
    }
}
