//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayLocNuoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class danhgia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public danhgia()
        {
            this.comments = new HashSet<comment>();
            this.liKedgs = new HashSet<liKedg>();
        }
    
        public int idDG { get; set; }
        public string noidung { get; set; }
        public Nullable<int> sosao { get; set; }
        public Nullable<int> solike { get; set; }
        public Nullable<bool> daxoa { get; set; }
        public Nullable<int> idSP { get; set; }
        public string taikhoan { get; set; }
    
        public virtual acc acc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments { get; set; }
        public virtual sanpham sanpham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<liKedg> liKedgs { get; set; }
    }
}
