//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayLocNuoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gioithieu
    {
        public int idGT { get; set; }
        public string cmoment { get; set; }
        public string anh { get; set; }
        public string anh1 { get; set; }
        public Nullable<bool> daxoa { get; set; }
        public Nullable<int> idSP { get; set; }
    
        public virtual sanpham sanpham { get; set; }
    }
}
