//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayLocNuoc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class mayLocNuocEntities : DbContext
    {
        public mayLocNuocEntities()
            : base("name=mayLocNuocEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<acc> accs { get; set; }
        public virtual DbSet<chucvu> chucvus { get; set; }
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<daMua> daMuas { get; set; }
        public virtual DbSet<dangMua> dangMuas { get; set; }
        public virtual DbSet<danhgia> danhgias { get; set; }
        public virtual DbSet<giohang> giohangs { get; set; }
        public virtual DbSet<gioithieu> gioithieux { get; set; }
        public virtual DbSet<info> infoes { get; set; }
        public virtual DbSet<infodelete> infodeletes { get; set; }
        public virtual DbSet<liKe1> liKe1 { get; set; }
        public virtual DbSet<liKedg> liKedgs { get; set; }
        public virtual DbSet<loai> loais { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<sanpham> sanphams { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        [DbFunction("mayLocNuocEntities", "F_cungHang")]
        public virtual IQueryable<F_cungHang_Result> F_cungHang(Nullable<int> idsp)
        {
            var idspParameter = idsp.HasValue ?
                new ObjectParameter("idsp", idsp) :
                new ObjectParameter("idsp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_cungHang_Result>("[mayLocNuocEntities].[F_cungHang](@idsp)", idspParameter);
        }
    
        [DbFunction("mayLocNuocEntities", "f_DanhGiaCaoNhat")]
        public virtual IQueryable<f_DanhGiaCaoNhat_Result> f_DanhGiaCaoNhat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_DanhGiaCaoNhat_Result>("[mayLocNuocEntities].[f_DanhGiaCaoNhat]()");
        }
    
        [DbFunction("mayLocNuocEntities", "f_DanhGiaCuaHang")]
        public virtual IQueryable<f_DanhGiaCuaHang_Result> f_DanhGiaCuaHang(string tk)
        {
            var tkParameter = tk != null ?
                new ObjectParameter("tk", tk) :
                new ObjectParameter("tk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_DanhGiaCuaHang_Result>("[mayLocNuocEntities].[f_DanhGiaCuaHang](@tk)", tkParameter);
        }
    
        [DbFunction("mayLocNuocEntities", "f_DoanhThuNgayTrongThang")]
        public virtual IQueryable<f_DoanhThuNgayTrongThang_Result> f_DoanhThuNgayTrongThang(string tk, Nullable<int> thang, Nullable<int> nam, Nullable<int> ngay)
        {
            var tkParameter = tk != null ?
                new ObjectParameter("tk", tk) :
                new ObjectParameter("tk", typeof(string));
    
            var thangParameter = thang.HasValue ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_DoanhThuNgayTrongThang_Result>("[mayLocNuocEntities].[f_DoanhThuNgayTrongThang](@tk, @thang, @nam, @ngay)", tkParameter, thangParameter, namParameter, ngayParameter);
        }
    
        [DbFunction("mayLocNuocEntities", "f_DoanhThuTrongNgay")]
        public virtual IQueryable<f_DoanhThuTrongNgay_Result> f_DoanhThuTrongNgay(string tk, Nullable<int> thang, Nullable<int> nam, Nullable<int> ngay)
        {
            var tkParameter = tk != null ?
                new ObjectParameter("tk", tk) :
                new ObjectParameter("tk", typeof(string));
    
            var thangParameter = thang.HasValue ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_DoanhThuTrongNgay_Result>("[mayLocNuocEntities].[f_DoanhThuTrongNgay](@tk, @thang, @nam, @ngay)", tkParameter, thangParameter, namParameter, ngayParameter);
        }
    
        [DbFunction("mayLocNuocEntities", "f_DoanhThuTrongThang")]
        public virtual IQueryable<f_DoanhThuTrongThang_Result> f_DoanhThuTrongThang(string tk, Nullable<int> thang, Nullable<int> nam)
        {
            var tkParameter = tk != null ?
                new ObjectParameter("tk", tk) :
                new ObjectParameter("tk", typeof(string));
    
            var thangParameter = thang.HasValue ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_DoanhThuTrongThang_Result>("[mayLocNuocEntities].[f_DoanhThuTrongThang](@tk, @thang, @nam)", tkParameter, thangParameter, namParameter);
        }
    
        [DbFunction("mayLocNuocEntities", "F_HienThiTatCarTaiKhoan")]
        public virtual IQueryable<F_HienThiTatCarTaiKhoan_Result> F_HienThiTatCarTaiKhoan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_HienThiTatCarTaiKhoan_Result>("[mayLocNuocEntities].[F_HienThiTatCarTaiKhoan]()");
        }
    
        [DbFunction("mayLocNuocEntities", "F_layComment")]
        public virtual IQueryable<F_layComment_Result> F_layComment(Nullable<int> idDG)
        {
            var idDGParameter = idDG.HasValue ?
                new ObjectParameter("idDG", idDG) :
                new ObjectParameter("idDG", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_layComment_Result>("[mayLocNuocEntities].[F_layComment](@idDG)", idDGParameter);
        }
    
        [DbFunction("mayLocNuocEntities", "F_laydanhdia")]
        public virtual IQueryable<F_laydanhdia_Result> F_laydanhdia(Nullable<int> idsp)
        {
            var idspParameter = idsp.HasValue ?
                new ObjectParameter("idsp", idsp) :
                new ObjectParameter("idsp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_laydanhdia_Result>("[mayLocNuocEntities].[F_laydanhdia](@idsp)", idspParameter);
        }
    
        [DbFunction("mayLocNuocEntities", "F_LayRaSanPhamCuaNhaCungCapMaKhachDaLapDatThanhCong")]
        public virtual IQueryable<F_LayRaSanPhamCuaNhaCungCapMaKhachDaLapDatThanhCong_Result> F_LayRaSanPhamCuaNhaCungCapMaKhachDaLapDatThanhCong(string tk)
        {
            var tkParameter = tk != null ?
                new ObjectParameter("tk", tk) :
                new ObjectParameter("tk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_LayRaSanPhamCuaNhaCungCapMaKhachDaLapDatThanhCong_Result>("[mayLocNuocEntities].[F_LayRaSanPhamCuaNhaCungCapMaKhachDaLapDatThanhCong](@tk)", tkParameter);
        }
    
        [DbFunction("mayLocNuocEntities", "F_LayRaSanPhamCuaNhaCungCapMaKhachDaMua")]
        public virtual IQueryable<F_LayRaSanPhamCuaNhaCungCapMaKhachDaMua_Result> F_LayRaSanPhamCuaNhaCungCapMaKhachDaMua(string tk)
        {
            var tkParameter = tk != null ?
                new ObjectParameter("tk", tk) :
                new ObjectParameter("tk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_LayRaSanPhamCuaNhaCungCapMaKhachDaMua_Result>("[mayLocNuocEntities].[F_LayRaSanPhamCuaNhaCungCapMaKhachDaMua](@tk)", tkParameter);
        }
    
        [DbFunction("mayLocNuocEntities", "F_laySanPham")]
        public virtual IQueryable<F_laySanPham_Result> F_laySanPham(Nullable<int> idsp)
        {
            var idspParameter = idsp.HasValue ?
                new ObjectParameter("idsp", idsp) :
                new ObjectParameter("idsp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_laySanPham_Result>("[mayLocNuocEntities].[F_laySanPham](@idsp)", idspParameter);
        }
    
        [DbFunction("mayLocNuocEntities", "f_TimKiemTheoTen")]
        public virtual IQueryable<f_TimKiemTheoTen_Result> f_TimKiemTheoTen(string truyenvao)
        {
            var truyenvaoParameter = truyenvao != null ?
                new ObjectParameter("truyenvao", truyenvao) :
                new ObjectParameter("truyenvao", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_TimKiemTheoTen_Result>("[mayLocNuocEntities].[f_TimKiemTheoTen](@truyenvao)", truyenvaoParameter);
        }
    
        [DbFunction("mayLocNuocEntities", "F_Top10DanhGiaCao")]
        public virtual IQueryable<F_Top10DanhGiaCao_Result> F_Top10DanhGiaCao(Nullable<int> top)
        {
            var topParameter = top.HasValue ?
                new ObjectParameter("top", top) :
                new ObjectParameter("top", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_Top10DanhGiaCao_Result>("[mayLocNuocEntities].[F_Top10DanhGiaCao](@top)", topParameter);
        }
    
        [DbFunction("mayLocNuocEntities", "F_TopBanChay")]
        public virtual IQueryable<F_TopBanChay_Result> F_TopBanChay(Nullable<int> top)
        {
            var topParameter = top.HasValue ?
                new ObjectParameter("top", top) :
                new ObjectParameter("top", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_TopBanChay_Result>("[mayLocNuocEntities].[F_TopBanChay](@top)", topParameter);
        }
    
        public virtual int P_themtaikhoan(string taikhoan, string matkhau, string email, ObjectParameter themtaikhoantrave)
        {
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_themtaikhoan", taikhoanParameter, matkhauParameter, emailParameter, themtaikhoantrave);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        [DbFunction("mayLocNuocEntities", "f_layChiTietDanhGia")]
        public virtual IQueryable<f_layChiTietDanhGia_Result> f_layChiTietDanhGia(string tk)
        {
            var tkParameter = tk != null ?
                new ObjectParameter("tk", tk) :
                new ObjectParameter("tk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_layChiTietDanhGia_Result>("[mayLocNuocEntities].[f_layChiTietDanhGia](@tk)", tkParameter);
        }
    
        [DbFunction("mayLocNuocEntities", "f_layrasosao")]
        public virtual IQueryable<f_layrasosao_Result> f_layrasosao(string tk)
        {
            var tkParameter = tk != null ?
                new ObjectParameter("tk", tk) :
                new ObjectParameter("tk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_layrasosao_Result>("[mayLocNuocEntities].[f_layrasosao](@tk)", tkParameter);
        }
    
        [DbFunction("mayLocNuocEntities", "f_layrasosaoSanPham")]
        public virtual IQueryable<f_layrasosaoSanPham_Result> f_layrasosaoSanPham(string tk, Nullable<int> idSP)
        {
            var tkParameter = tk != null ?
                new ObjectParameter("tk", tk) :
                new ObjectParameter("tk", typeof(string));
    
            var idSPParameter = idSP.HasValue ?
                new ObjectParameter("idSP", idSP) :
                new ObjectParameter("idSP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_layrasosaoSanPham_Result>("[mayLocNuocEntities].[f_layrasosaoSanPham](@tk, @idSP)", tkParameter, idSPParameter);
        }
    
        [DbFunction("mayLocNuocEntities", "f_layChiTietDanhGiaTheoSoSao")]
        public virtual IQueryable<f_layChiTietDanhGiaTheoSoSao_Result> f_layChiTietDanhGiaTheoSoSao(string tk, Nullable<int> sao)
        {
            var tkParameter = tk != null ?
                new ObjectParameter("tk", tk) :
                new ObjectParameter("tk", typeof(string));
    
            var saoParameter = sao.HasValue ?
                new ObjectParameter("sao", sao) :
                new ObjectParameter("sao", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_layChiTietDanhGiaTheoSoSao_Result>("[mayLocNuocEntities].[f_layChiTietDanhGiaTheoSoSao](@tk, @sao)", tkParameter, saoParameter);
        }
    
        [DbFunction("mayLocNuocEntities", "f_DanhGiaCaoNhatNhaCungCap")]
        public virtual IQueryable<f_DanhGiaCaoNhatNhaCungCap_Result> f_DanhGiaCaoNhatNhaCungCap(string tk)
        {
            var tkParameter = tk != null ?
                new ObjectParameter("tk", tk) :
                new ObjectParameter("tk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_DanhGiaCaoNhatNhaCungCap_Result>("[mayLocNuocEntities].[f_DanhGiaCaoNhatNhaCungCap](@tk)", tkParameter);
        }
    
        [DbFunction("mayLocNuocEntities", "f_DanhGiaThapNhatNhaCungCap")]
        public virtual IQueryable<f_DanhGiaThapNhatNhaCungCap_Result> f_DanhGiaThapNhatNhaCungCap(string tk)
        {
            var tkParameter = tk != null ?
                new ObjectParameter("tk", tk) :
                new ObjectParameter("tk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_DanhGiaThapNhatNhaCungCap_Result>("[mayLocNuocEntities].[f_DanhGiaThapNhatNhaCungCap](@tk)", tkParameter);
        }
    }
}
