//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayLocNuoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCungCap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaCungCap()
        {
            this.sanphams = new HashSet<sanpham>();
        }
    
        public int idIfncc { get; set; }
        public string nameFull { get; set; }
        public int age { get; set; }
        public string number_phone { get; set; }
        public string adress { get; set; }
        public string ATM { get; set; }
        public int idhopdong { get; set; }
        public Nullable<bool> daxoa { get; set; }
        public string taikhoan { get; set; }
        public string About { get; set; }
    
        public virtual acc acc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sanpham> sanphams { get; set; }
    }
}
